"""Enumerations shared across the pipeline.

The run status marks whether a run consumed internal research data only or
whether external validation data was involved. Historical curated runs use
INTERNAL_RESEARCH exclusively.
"""

from __future__ import annotations

RUN_STATUS_INTERNAL = "INTERNAL_RESEARCH"
RUN_STATUS_EXTERNAL = "EXTERNAL_VALIDATION"
RUN_STATUS_VALUES = (RUN_STATUS_INTERNAL, RUN_STATUS_EXTERNAL)

DECISION_LOCALIZED = "LOCALIZED"
DECISION_ABSTAIN = "ABSTAIN"
DECISION_VALUES = (DECISION_LOCALIZED, DECISION_ABSTAIN)

REASON_AMBIGUOUS_STAGES = "AMBIGUOUS_STAGES"
REASON_INSUFFICIENT_BASELINE = "INSUFFICIENT_BASELINE"
REASON_NOT_COMPARABLE_SITE = "NOT_COMPARABLE_SITE"
REASON_VALUES = (REASON_AMBIGUOUS_STAGES, REASON_INSUFFICIENT_BASELINE, REASON_NOT_COMPARABLE_SITE)

EVENT_DELAY = "DELAY"
EVENT_REWORK = "REWORK"
EVENT_VALUES = (EVENT_DELAY, EVENT_REWORK)

PERMISSIONS_POINTER = "research/permissions.md"
OPERATOR = "researcher"
